import { Elysia } from 'elysia'
import { appLog } from '../../lib/applog'
import { requireSuperAdmin } from '../../lib/auth-middleware'
import { prisma } from '../../lib/db'
import { redis } from '../../lib/redis'

// Tabel dalam urutan parent → child untuk insert.
// Reverse untuk truncate (CASCADE menangani FK).
// _prisma_migrations TIDAK ikut — biarkan history migration local utuh.
const TABLES_INSERT_ORDER = [
  'user',
  'verification',
  'account',
  'session',
  'audit_log',
  'gist',
  'api_token',
  'portainer_connection',
  'project',
  'project_member',
  'project_note',
  'environment',
  'portainer_config',
  'ticket',
  'env_var',
  'portainer_sync_log',
  'portainer_stack_target',
  'ticket_comment',
  'ticket_evidence',
] as const

type TableName = (typeof TABLES_INSERT_ORDER)[number]

const TOKEN_PREFIX = 'db:sync:'
const TOKEN_TTL_SECONDS = 300

export const databaseRouter = new Elysia()

  // ─── Generate one-time sync token (di STG) ───────────────────────────────────
  .post('/api/envman/database/sync-token', async ({ request, set }) => {
    const caller = await requireSuperAdmin(request)
    if (!caller) {
      set.status = 403
      return { error: 'SUPER_ADMIN required' }
    }
    const token = crypto.randomUUID()
    await redis.set(TOKEN_PREFIX + token, caller.userId, 'EX', String(TOKEN_TTL_SECONDS))
    appLog('info', `DB sync token generated by ${caller.email}`)
    return { token, expiresInSeconds: TOKEN_TTL_SECONDS }
  })

  // ─── Stream NDJSON dump (dipanggil oleh local dev) ───────────────────────────
  .get('/api/envman/database/sync-dump', async ({ request, set }) => {
    const token = request.headers.get('x-sync-token') ?? ''
    if (!token) {
      set.status = 401
      return { error: 'Missing X-Sync-Token header' }
    }

    // Atomic single-use: GETDEL — get and delete dalam satu operasi
    let issuedByUserId: string | null = null
    try {
      issuedByUserId = (await redis.send('GETDEL', [TOKEN_PREFIX + token])) as string | null
    } catch {
      // Fallback kalau GETDEL tidak didukung: get + del (race window kecil)
      issuedByUserId = await redis.get(TOKEN_PREFIX + token)
      if (issuedByUserId) await redis.del(TOKEN_PREFIX + token).catch(() => {})
    }
    if (!issuedByUserId) {
      set.status = 401
      return { error: 'Invalid or expired token' }
    }

    appLog('info', `DB sync dump streaming (token from user ${issuedByUserId})`)

    const encoder = new TextEncoder()
    const stream = new ReadableStream({
      async start(controller) {
        try {
          for (const table of TABLES_INSERT_ORDER) {
            const rows = await prisma.$queryRawUnsafe<unknown[]>(`SELECT * FROM "${table}"`)
            const line = `${JSON.stringify({ table, rows })}\n`
            controller.enqueue(encoder.encode(line))
          }
          controller.close()
        } catch (e) {
          appLog('error', 'DB sync dump failed', String(e))
          controller.error(e)
        }
      },
    })

    return new Response(stream, {
      headers: {
        'Content-Type': 'application/x-ndjson',
        'Cache-Control': 'no-store',
      },
    })
  })

  // ─── Fetch from remote + restore ke local (dipanggil dari UI local) ──────────
  .post('/api/envman/database/sync-from', async ({ request, set }) => {
    if (process.env.NODE_ENV === 'production') {
      set.status = 403
      return { error: 'Sync target disabled in production' }
    }
    const caller = await requireSuperAdmin(request)
    if (!caller) {
      set.status = 403
      return { error: 'SUPER_ADMIN required' }
    }

    const body = (await request.json().catch(() => null)) as { url?: string; token?: string } | null
    if (!body?.url || !body?.token) {
      set.status = 400
      return { error: 'url and token required' }
    }
    let sourceUrl: URL
    try {
      sourceUrl = new URL(body.url)
    } catch {
      set.status = 400
      return { error: 'Invalid url' }
    }
    if (sourceUrl.protocol !== 'http:' && sourceUrl.protocol !== 'https:') {
      set.status = 400
      return { error: 'url must be http or https' }
    }
    const dumpUrl = `${sourceUrl.origin}/api/envman/database/sync-dump`

    const started = performance.now()
    let res: Response
    try {
      res = await fetch(dumpUrl, { headers: { 'X-Sync-Token': body.token } })
    } catch (e) {
      set.status = 502
      return { error: `Failed to reach source: ${String(e)}` }
    }
    if (!res.ok) {
      const errText = await res.text().catch(() => '')
      set.status = res.status
      return { error: `Source returned ${res.status}: ${errText.slice(0, 200)}` }
    }
    if (!res.body) {
      set.status = 502
      return { error: 'Empty response body from source' }
    }

    // Parse NDJSON stream → kumpulkan ke map { table: rows[] }
    const tableData = new Map<TableName, unknown[]>()
    const reader = res.body.getReader()
    const decoder = new TextDecoder()
    let buffer = ''
    try {
      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        buffer += decoder.decode(value, { stream: true })
        let nl: number = buffer.indexOf('\n')
        while (nl >= 0) {
          const line = buffer.slice(0, nl).trim()
          buffer = buffer.slice(nl + 1)
          nl = buffer.indexOf('\n')
          if (!line) continue
          try {
            const parsed = JSON.parse(line) as { table: TableName; rows: unknown[] }
            if (parsed.table && Array.isArray(parsed.rows)) {
              tableData.set(parsed.table, parsed.rows)
            }
          } catch (e) {
            appLog('warn', `DB sync: skipped malformed line`, String(e))
          }
        }
      }
      // Sisa buffer (tanpa newline trailing)
      const trailing = buffer.trim()
      if (trailing) {
        try {
          const parsed = JSON.parse(trailing) as { table: TableName; rows: unknown[] }
          if (parsed.table && Array.isArray(parsed.rows)) {
            tableData.set(parsed.table, parsed.rows)
          }
        } catch {
          /* ignore */
        }
      }
    } catch (e) {
      set.status = 502
      return { error: `Stream read failed: ${String(e)}` }
    }

    // Restore dalam transaction
    const summary: Record<string, number> = {}
    try {
      await prisma.$transaction(
        async (tx) => {
          // Truncate semua tabel sekaligus dengan CASCADE — atomic, FK aman
          const truncateList = TABLES_INSERT_ORDER.map((t) => `"${t}"`).join(', ')
          await tx.$executeRawUnsafe(`TRUNCATE TABLE ${truncateList} CASCADE`)

          // Insert parent → child
          for (const table of TABLES_INSERT_ORDER) {
            const rows = tableData.get(table) ?? []
            if (rows.length === 0) {
              summary[table] = 0
              continue
            }
            // Build INSERT manual karena kolom heterogen per tabel
            const keys = Object.keys(rows[0] as object)
            if (keys.length === 0) {
              summary[table] = 0
              continue
            }
            const colList = keys.map((k) => `"${k}"`).join(', ')
            // Insert batch (chunk 500 untuk hindari paket terlalu besar)
            const CHUNK = 500
            for (let i = 0; i < rows.length; i += CHUNK) {
              const chunk = rows.slice(i, i + CHUNK)
              const values: unknown[] = []
              const placeholders = chunk
                .map((row, rIdx) => {
                  const ph = keys.map((_, kIdx) => `$${rIdx * keys.length + kIdx + 1}`).join(', ')
                  for (const k of keys) values.push((row as Record<string, unknown>)[k])
                  return `(${ph})`
                })
                .join(', ')
              await tx.$executeRawUnsafe(`INSERT INTO "${table}" (${colList}) VALUES ${placeholders}`, ...values)
            }
            summary[table] = rows.length
          }
        },
        { timeout: 60_000, maxWait: 10_000 },
      )
    } catch (e) {
      appLog('error', 'DB sync restore failed', String(e))
      set.status = 500
      return { error: `Restore failed: ${String(e)}` }
    }

    // Clear cache (project list per user, access, dll) — fire-and-forget
    redis.send('FLUSHDB', []).catch(() => {})

    const durationMs = Math.round(performance.now() - started)
    appLog('info', `DB sync restore OK (${durationMs}ms)`)
    return { ok: true, tables: summary, durationMs }
  })
