export const ROUTE_MANIFEST: { method: string; path: string; auth: string; category: string; description: string }[] =
  [
    // Frontend routes
    { method: 'PAGE', path: '/', auth: 'public', category: 'frontend', description: 'Landing page' },
    {
      method: 'PAGE',
      path: '/login',
      auth: 'public',
      category: 'frontend',
      description: 'Login page (email/password + Google OAuth)',
    },
    {
      method: 'PAGE',
      path: '/dev',
      auth: 'superAdmin',
      category: 'frontend',
      description: 'Dev console (SUPER_ADMIN only)',
    },
    {
      method: 'PAGE',
      path: '/dashboard',
      auth: 'admin',
      category: 'frontend',
      description: 'Admin dashboard (ADMIN+)',
    },
    {
      method: 'PAGE',
      path: '/profile',
      auth: 'authenticated',
      category: 'frontend',
      description: 'User profile (all authenticated)',
    },
    {
      method: 'PAGE',
      path: '/blocked',
      auth: 'authenticated',
      category: 'frontend',
      description: 'Blocked user info page',
    },
    // Auth
    {
      method: 'POST',
      path: '/api/auth/login',
      auth: 'public',
      category: 'auth',
      description: 'Email/password login',
    },
    {
      method: 'POST',
      path: '/api/auth/logout',
      auth: 'authenticated',
      category: 'auth',
      description: 'Logout (delete session)',
    },
    {
      method: 'GET',
      path: '/api/auth/session',
      auth: 'public',
      category: 'auth',
      description: 'Check current session',
    },
    {
      method: 'GET',
      path: '/api/auth/google',
      auth: 'public',
      category: 'auth',
      description: 'Google OAuth redirect',
    },
    {
      method: 'GET',
      path: '/api/auth/callback/google',
      auth: 'public',
      category: 'auth',
      description: 'Google OAuth callback',
    },
    // Dev Auth
    {
      method: 'GET',
      path: '/api/dev-auth/login-as/:email',
      auth: 'public',
      category: 'auth',
      description: 'Dev-only: login as any user by email (development only)',
    },
    // Admin
    {
      method: 'GET',
      path: '/api/admin/users',
      auth: 'superAdmin',
      category: 'admin',
      description: 'List all users',
    },
    {
      method: 'PUT',
      path: '/api/admin/users/:id/role',
      auth: 'superAdmin',
      category: 'admin',
      description: 'Change user role',
    },
    {
      method: 'PUT',
      path: '/api/admin/users/:id/block',
      auth: 'superAdmin',
      category: 'admin',
      description: 'Block/unblock user',
    },
    {
      method: 'GET',
      path: '/api/admin/presence',
      auth: 'superAdmin',
      category: 'admin',
      description: 'Online user IDs',
    },
    {
      method: 'GET',
      path: '/api/admin/logs/app',
      auth: 'superAdmin',
      category: 'admin',
      description: 'App logs (Redis)',
    },
    {
      method: 'GET',
      path: '/api/admin/logs/audit',
      auth: 'superAdmin',
      category: 'admin',
      description: 'Audit logs (DB)',
    },
    {
      method: 'DELETE',
      path: '/api/admin/logs/app',
      auth: 'superAdmin',
      category: 'admin',
      description: 'Clear app logs',
    },
    {
      method: 'DELETE',
      path: '/api/admin/logs/audit',
      auth: 'superAdmin',
      category: 'admin',
      description: 'Clear audit logs',
    },
    {
      method: 'GET',
      path: '/api/admin/schema',
      auth: 'superAdmin',
      category: 'admin',
      description: 'Database schema (Prisma)',
    },
    {
      method: 'GET',
      path: '/api/admin/routes',
      auth: 'superAdmin',
      category: 'admin',
      description: 'Routes metadata',
    },
    {
      method: 'GET',
      path: '/api/admin/project-structure',
      auth: 'superAdmin',
      category: 'admin',
      description: 'Project file structure',
    },
    {
      method: 'GET',
      path: '/api/admin/env-map',
      auth: 'superAdmin',
      category: 'admin',
      description: 'Environment variables map',
    },
    {
      method: 'GET',
      path: '/api/admin/test-coverage',
      auth: 'superAdmin',
      category: 'admin',
      description: 'Test coverage mapping',
    },
    {
      method: 'GET',
      path: '/api/admin/dependencies',
      auth: 'superAdmin',
      category: 'admin',
      description: 'NPM dependencies graph',
    },
    {
      method: 'GET',
      path: '/api/admin/migrations',
      auth: 'superAdmin',
      category: 'admin',
      description: 'Migration timeline',
    },
    {
      method: 'GET',
      path: '/api/admin/sessions',
      auth: 'superAdmin',
      category: 'admin',
      description: 'Active sessions (live)',
    },
    // Tickets
    {
      method: 'GET',
      path: '/api/tickets',
      auth: 'qcOrAdmin',
      category: 'tickets',
      description: 'List tickets (filter: status, priority, assigneeId)',
    },
    {
      method: 'POST',
      path: '/api/tickets',
      auth: 'qcOrAdmin',
      category: 'tickets',
      description: 'Create ticket (QC/ADMIN/SUPER_ADMIN)',
    },
    {
      method: 'GET',
      path: '/api/tickets/:id',
      auth: 'qcOrAdmin',
      category: 'tickets',
      description: 'Get ticket detail with comments and evidence',
    },
    {
      method: 'PATCH',
      path: '/api/tickets/:id',
      auth: 'qcOrAdmin',
      category: 'tickets',
      description: 'Update ticket fields (role-based status transitions)',
    },
    {
      method: 'POST',
      path: '/api/tickets/:id/comments',
      auth: 'qcOrAdmin',
      category: 'tickets',
      description: 'Add comment to ticket',
    },
    {
      method: 'POST',
      path: '/api/tickets/:id/evidence',
      auth: 'qcOrAdmin',
      category: 'tickets',
      description: 'Attach evidence (screenshot, commit, test log)',
    },
    // Utility
    { method: 'GET', path: '/health', auth: 'public', category: 'utility', description: 'Health check' },
    {
      method: 'GET',
      path: '/api/version',
      auth: 'public',
      category: 'utility',
      description: 'App name and version from package.json',
    },
    { method: 'GET', path: '/api/hello', auth: 'public', category: 'utility', description: 'Hello world (GET)' },
    { method: 'PUT', path: '/api/hello', auth: 'public', category: 'utility', description: 'Hello world (PUT)' },
    {
      method: 'GET',
      path: '/api/hello/:name',
      auth: 'public',
      category: 'utility',
      description: 'Hello with name param',
    },
    // WebSocket
    {
      method: 'WS',
      path: '/ws/presence',
      auth: 'authenticated',
      category: 'realtime',
      description: 'Real-time presence tracking',
    },
  ]
